name: Python Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: smart_home_env
          python-version: 3.10
          channels: conda-forge,defaults
          auto-activate-base: false

      - name: Update Conda and create environment
        run: conda env update --file environment.yml --name smart_home_env

      - name: Activate Conda environment and Run tests
        run: |
          source activate smart_home_env
          python -m unittest discover -s . -p 'test_*.py'
